import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Slider from '../components/Slider/Slider'
import AddToCart from '../components/Modal/AddToCart'
import ViewProduct from '../components/Modal/ViewProduct'
export default function Home() {
  return (
    <div >
      <Head>
        <title>web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
     <Slider />

     <div className="product-tab-section section-top-gap-100">
      
        <div className="section-content-gap">
            <div className="container-fluid">
                <div className="row">
                    <div className="section-content d-flex justify-content-between align-items-md-center align-items-start flex-md-row flex-column">
                        <h3 className="section-title">New Arrivals</h3>
                        <ul className="tablist nav product-tab-btn">
                            <li><a className="nav-link active" data-toggle="tab" href="#car_and_drive">Car & Drive </a></li>
                            <li><a className="nav-link" data-toggle="tab" href="#motorcycle">Motorcycle</a></li>
                            <li><a className="nav-link" data-toggle="tab" href="#truck_drive">Truck & Drive</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div className="product-tab-wrapper">
            <div className="container-fluid">
                <div className="row">
                    <div className="col-12">
                        <div className="tab-content tab-animate-zoom">
                            <div className="tab-pane show active" id="car_and_drive">
                                <div className="product-default-slider product-default-slider-4grids-1row">
                                  
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_2.jpg" 
                                                alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_1.jpg" 
                                                alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_4.jpg" 
                                                alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div>
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_3.jpg"
                                                 alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_6.jpg"
                                                 alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div>
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_5.jpg"
                                                 alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_8.jpg" 
                                                alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_7.jpg" 
                                                alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                </div>
                            </div>
                            <div className="tab-pane" id="motorcycle">
                                <div className="product-default-slider product-default-slider-4grids-1row">
                                 
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_1.jpg" 
                                                alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div>
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_2.jpg" 
                                                alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div>
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_3.jpg" 
                                                alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_4.jpg" 
                                                alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_5.jpg"
                                                 alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_6.jpg" 
                                                alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_8.jpg"
                                                 alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div>
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_7.jpg"
                                                 alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                </div>
                            </div>
                            <div className="tab-pane" id="truck_drive">
                                <div className="product-default-slider product-default-slider-4grids-1row">
                                  
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_8.jpg" 
                                                alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_7.jpg"
                                                 alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div>
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_6.jpg"
                                                 alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div>
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_5.jpg"
                                                 alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_4.jpg" 
                                                alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_3.jpg"
                                                 alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div>
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_2.jpg" 
                                                alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div>
                                    <div className="product-default-single border-around">
                                        <div className="product-img-warp">
                                            <a href="product-details-default.html" className="product-default-img-link">
                                                <img src="assets/images/products_images/aments_products_image_1.jpg"
                                                 alt="" className="product-default-img img-fluid"/>
                                            </a>
                                            <div className="product-action-icon-link">
                                                <ul>
                                                    <li><a href="wishlist.html"><i className="icon-heart"></i></a></li>
                                                    <li><a href="compare.html"><i className="icon-repeat"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalQuickview"><i className="icon-eye"></i></a></li>
                                                    <li><a href="#" data-toggle="modal" data-target="#modalAddcart"><i className="icon-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="product-default-content">
                                            <h6 className="product-default-link"><a href="product-details-default.html">New Balance Tyres</a></h6>
                                            <span className="product-default-price"><del className="product-default-price-off">$30.12</del> $25.12</span>
                                        </div>
                                    </div> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 

    </div>

<AddToCart />
<ViewProduct />
      </main>

      
    </div>
  )
}
